PROVINCE_DICT = {'01' : 'dolnośląskie',
'02' : 'kujawsko-pomorskie',
'03' : 'lubelskie',
'04' : 'lubuskie',
'05' : 'łódzkie',
'06' : 'małopolskie',
'07' : 'mazowieckie',
'08' : 'opolskie',
'09' : 'podkarpackie',
'10' : 'podlaskie',
'11' : 'pomorskie',
'12' : 'śląskie',
'13' : 'świętokrzyskie',
'14' : 'warmińsko-mazurskie',
'15' : 'wielkopolskie',
'16' : 'zachodniopomorskie'}

VIEW_DICT = {'benefit': "USŁUGA",
 'provider': "ŚWIADCZENIODAWCA",
 'regon-provider': "REGON",
 'nip-provider': "NIP",
 'place': "MIEJSCE",
 'address': "ADRES",
 'locality': "MIEJSCOWOŚĆ",
 'phone': "TELEFON",
 'benefits-for-children': "ŚWIADCZENIA DLA DZIECI",
 'distance': "ODLEGŁOŚĆ (KM)"}